version: "2"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    command: bash -i -c 'bundle exec rails server -p 3000 -b 0.0.0.0'
    container_name: redmine_add_to_calender
    restart: always
